apiVersion: v1
kind: ConfigMap
metadata:
  name: assignment-agentic-ai-config
  namespace: default
  labels:
    app: assignment-agentic-ai
data:
  MODEL_NAME: "gpt-4o-mini"
  EMBEDDING_MODEL: "text-embedding-3-small"
  APP_PORT: "8000"
